# Generated by Django 6.0.5 on 2026-06-02 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('titulo_profesional', models.CharField(max_length=180)),
                ('ubicacion', models.CharField(default='Bolivia', max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('descripcion_corta', models.CharField(max_length=280)),
                ('descripcion_larga', models.TextField()),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='perfil/')),
                ('github_url', models.URLField(blank=True)),
                ('disponible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('descripcion_corta', models.CharField(max_length=280)),
                ('descripcion_profesional', models.TextField()),
                ('categoria', models.CharField(max_length=100)),
                ('repo_nombre', models.CharField(blank=True, max_length=150)),
                ('repo_url', models.URLField(blank=True)),
                ('demo_url', models.URLField(blank=True)),
                ('destacado', models.BooleanField(default=False)),
                ('visible', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['orden', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='RedSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('url', models.URLField()),
                ('icono', models.CharField(help_text='Clase de icono, por ejemplo: bi bi-github.', max_length=80)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Red social',
                'verbose_name_plural': 'Redes sociales',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('descripcion', models.TextField()),
                ('icono', models.CharField(blank=True, help_text='Clase de icono, por ejemplo: bi bi-braces.', max_length=80)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['orden', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('categoria', models.CharField(max_length=80)),
                ('icono', models.CharField(blank=True, help_text='Clase de icono o identificador visual.', max_length=80)),
                ('color', models.CharField(blank=True, help_text='Color hexadecimal opcional, por ejemplo: #00e5ff.', max_length=20)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tecnología',
                'verbose_name_plural': 'Tecnologías',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ProyectoImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='proyectos/')),
                ('titulo', models.CharField(max_length=120)),
                ('descripcion', models.CharField(blank=True, max_length=240)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('visible', models.BooleanField(default=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='portafolio.proyecto')),
            ],
            options={
                'verbose_name': 'Imagen de proyecto',
                'verbose_name_plural': 'Imágenes de proyecto',
                'ordering': ['orden', 'titulo'],
            },
        ),
        migrations.AddField(
            model_name='proyecto',
            name='tecnologias',
            field=models.ManyToManyField(blank=True, related_name='proyectos', to='portafolio.tecnologia'),
        ),
    ]
