# Generated by Django 6.0.5 on 2026-06-03 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='cv_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='subtitulo_hero',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='perfil',
            name='telefono_whatsapp',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='perfil',
            name='texto_boton_principal',
            field=models.CharField(default='Ver proyectos', max_length=80),
        ),
        migrations.AddField(
            model_name='perfil',
            name='texto_boton_secundario',
            field=models.CharField(default='Contactarme', max_length=80),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='cliente',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fecha',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='mostrar_en_home',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='problema',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='resultado',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='solucion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proyectoimagen',
            name='es_portada',
            field=models.BooleanField(default=False),
        ),
    ]
