"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.
"""

import os
from pathlib import Path


# =========================
# Rutas base del proyecto
# =========================
BASE_DIR = Path(__file__).resolve().parent.parent


# =========================
# Seguridad y entorno
# =========================
# En producción, SECRET_KEY debe definirse como variable de entorno.
SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "clave-local-de-desarrollo-cambiar-en-produccion"
)

# En local queda True por defecto.
# En PythonAnywhere se debe usar DEBUG=False.
DEBUG = os.environ.get("DEBUG", "True") == "True"

# Hosts permitidos.
# En PythonAnywhere debe incluir jematti.pythonanywhere.com.
ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get(
        "ALLOWED_HOSTS",
        "jematti.pythonanywhere.com,127.0.0.1,localhost"
    ).split(",")
    if host.strip()
]

# Orígenes confiables para formularios/admin en producción.
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get(
        "CSRF_TRUSTED_ORIGINS",
        "https://jematti.pythonanywhere.com"
    ).split(",")
    if origin.strip()
]

# URL pública usada para sitemap.xml.
SITE_URL = os.environ.get(
    "SITE_URL",
    "https://jematti.pythonanywhere.com/"
)


# =========================
# Aplicaciones
# =========================
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Apps propias del proyecto
    "portafolio",
]


# =========================
# Middleware
# =========================
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# =========================
# URLs y WSGI
# =========================
ROOT_URLCONF = "config.urls"

WSGI_APPLICATION = "config.wsgi.application"


# =========================
# Templates
# =========================
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",

        # APP_DIRS=True permite encontrar templates dentro de:
        # portfolio/templates/
        "DIRS": [],

        "APP_DIRS": True,

        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


# =========================
# Base de datos
# =========================
# Para este portafolio CMS usamos SQLite.
# En una versión más avanzada puede migrarse a PostgreSQL.
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# =========================
# Validación de contraseñas
# =========================
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# =========================
# Internacionalización
# =========================
LANGUAGE_CODE = "es"

TIME_ZONE = "America/La_Paz"

USE_I18N = True

USE_TZ = True


# =========================
# Archivos estáticos
# =========================
# Archivos del sistema: CSS, JS, imágenes fijas del diseño.
STATIC_URL = "static/"

# Carpeta donde collectstatic junta los estáticos para producción.
STATIC_ROOT = BASE_DIR / "staticfiles"


# =========================
# Archivos media
# =========================
# Archivos subidos desde Django Admin:
# avatar, capturas de proyectos, imágenes del CMS.
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"


# =========================
# Campo ID por defecto
# =========================
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"